### ISSUE TITLE
Binary for Mac?

### ISSUE THREAD

**Issue by amanjpro** [mvanthoor/rustic#28]
I would love to put Rustic to my toolset. Whenever I implement something for Zahak, I tend to test it against other engines, and I will love to include Rustic to my set.

**Comment by mvanthoor** [comment]
Hi. To make binaries for a Mac, I'll have to use someone else's computer. I'll see what I can do, but as I don't have a Mac myself, I can't promise anything. I did see in the Talkchess forum that you have compiled Rustic yourself. Maybe you could be the Mac binary tester if I can get them made?

**Comment by amanjpro** [comment]
Sure, I have no problem testing them, as I am currently using rustic in my tournaments anyways

**Comment by amanjpro** [comment]
Would you also be able to use Zahak in your matches? I really want to have it tested on Windows, as I don't have a Windows box (an I have no access to it)

**Comment by mvanthoor** [comment]
I've been using Zahak in matches without problems (at least, version 0.3.0) There's only one graphical glitch in Cutechess: the top line (variation with the largest depth) flashes when Zahak is to move, as if the engine sends the same line over and over again or something. I haven't investigated this.

**Comment by amanjpro** [comment]
That is actually the case, as Zahak searches new moves it sends the PV again. If you look, the number of moves/time changes

**Comment by mvanthoor** [comment]
Binaries for Intel Mac will be included in the imminent release of Rustic Alpha 3.0.0 and further.

I have no M1 Mac, so I can't create binaries for those. (I do not want to create them automatically somewhere without testing.) I'm writing some build instructions for people who want to try and build Rustic themselves on CPU's or OS's I can't support.
